version: "3.9"
services:
  app1:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - APP_NAME=App1
  
  app2:
    build: .
    ports:
      - "3002:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - APP_NAME=App2
  
  app3:
      build: .
      ports:
        - "3003:3000"
      volumes:
        - .:/app
        - /app/node_modules
      environment:
        - NODE_ENV=development
        - APP_NAME=App3
